# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "asimov-camera-module"
version = "0.0.3"
authors = ["ASIMOV Community"]
edition = "2024"
#rust-version = "1.85"
description = "ASIMOV Camera module."
#documentation = "https://docs.rs/asimov-camera-module"
readme = true
homepage = "https://github.com/asimov-modules"
repository = "https://github.com/asimov-modules/asimov-camera-module"
license = "Unlicense"
keywords = ["asimov-module", "asimov", "ai"]
categories = ["command-line-utilities", "text-processing"] # TODO
publish = false
build = "build.rs"

[features]
default = ["cli", "std", "ffmpeg", "android", "avf"]
cli = [
  "asimov-module/cli",
  "std",
  "dep:clap",
  "dep:clientele",
  "dep:image",
  "dep:image_hasher",
  "dep:serde_json"
]
std = ["asimov-module/std", "clap?/std", "clientele?/std"]
pretty = []
tracing = ["asimov-module/tracing", "clientele?/tracing"]
mobile-preview = []
ffmpeg = []
android = ["mobile-preview", "dep:ndk-sys"]
avf = [
  "mobile-preview",
  "dep:dispatch2",
  "dep:objc2",
  "dep:objc2-av-foundation",
  "dep:objc2-core-foundation",
  "dep:objc2-core-media",
  "dep:objc2-core-video",
  "dep:objc2-foundation",
]

[dependencies]
asimov-module = { version = "25", default-features = false, features = ["std"] }
ctrlc = "3.5"
thiserror = "2"
bytes = "1"
crossbeam-channel = "0.5"
know = { version = "0.2", features = ["serde"] }

# Optional CLI-only dependencies:
clap = { version = "4.5", default-features = false, features = ["std"], optional = true }
clientele = { version = "0.3.8", default-features = false, features = ["clap", "std"], optional = true }
serde_json = { version = "1.0.145", optional = true }
image = { version = "0.25", optional = true }
image_hasher = { version = "3", features = ["fast_image_resize"], optional = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "android")'.dependencies]
ndk-sys = { version = "0.6", optional = true }

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
dispatch2 = { version = "0.3", optional = true }
objc2 = { version = "0.6", optional = true, features = ["exception"] }
objc2-av-foundation = { version = "0.3", features = ["objc2-core-media"], optional = true }
objc2-core-foundation = { version = "0.3", optional = true }
objc2-core-media = { version = "0.3", optional = true }
objc2-core-video = { version = "0.3", optional = true }
objc2-foundation = { version = "0.3", features = ["NSArray", "NSDictionary", "NSObject"], optional = true }

[profile.release]
opt-level = "z"
strip = true
lto = "thin"

[[bin]]
name = "asimov-camera-reader"
path = "src/bin/reader.rs"
required-features = ["cli"]

[[bin]]
name = "asimov-camera-cataloger"
path = "src/bin/cataloger.rs"
required-features = ["cli"]
